#if !defined(AFX_SIMULANIMAT_H__0C4BC7A5_F381_11D3_A2F4_00D0B71C8709__INCLUDED_)
#define AFX_SIMULANIMAT_H__0C4BC7A5_F381_11D3_A2F4_00D0B71C8709__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// SimulAnimat.h : header file
//

#include "Animation\MRTracker.h"
#include <MInstruction\LearningUnit.h>
#include <Animation\AnimObject.h>

class CFormatAnimation;
class CSectorObject;
class CSelectorDlg;

/////////////////////////////////////////////////////////////////////////////
// 
/////////////////////////////////////////////////////////////////////////////
class CAnimBar : public CToolBar
{
public:
	CComboBox   m_comboBox;
	CFont       m_font;
};


/////////////////////////////////////////////////////////////////////////////
/// Class used to implement the interface of an Animation ER.
///
/// The same interface is used in Authoring Mode (to create and modify the animation) and
/// in Learning Mode (to explore the simulation). In Authoring Mode, The Animation ER can be
/// used in Edit Mode (i.e. modifiable) and Test Mode (i.e. not modifiable, as in Learning Mode), 
/// specified by the #m_bShowProp attribute. 
/// The Animation Components displayed in the ER are stored in the CFormatAnimation::m_cObjSet attribute,
/// available by the #GetFormats() function.
/////////////////////////////////////////////////////////////////////////////
class CViewAnimat : public CScrollView
{
protected:
	CViewAnimat();           // protected constructor used by dynamic creation
	DECLARE_DYNCREATE(CViewAnimat)

// Attributes
protected:
	CToolBar			m_wndToolBar;
	CToolBar			m_wndAlignBar;
	CAnimBar			m_wndAnimBar;
	CToolTipCtrl		m_wndToolTip;
	CMultiRectTracker	m_wndMultiTrack;

	CSelectorDlg*		m_pSelectDlg;			///< Pointer to the Component Selector (Edit Mode only).
protected:
	CExternRepUnit*		m_pER;					///< Pointer to the External Representation associated with this view.

	CxAnimObjectList	m_cVisuObjSet;			///< OBSOLETE: List of components actually in the animation ER.
	CxAnimObjectList	m_cPredObjSet;			///< List of components generated by a Prediction.
	CSectorObject*		m_pBuiltInSector;		///< Pointer to the current Sector component used to build subsequent components (Edit Mode only).
	CAnimObject*		m_pObjDblClick;			///< Pointer to the last double-cliked component (Edit Mode only).

	int		m_currTime;					///< Contains the current time-step of the simulation
	int		m_currExpSet;				///< Contains the index of the current selected Experimental Set
	int		m_nPredDraw;				///< Location where the prediction will be displayed (0: right , 1: bottom).

	BOOL	m_bShowProp;				///< Switch the view between Edit Mode (TRUE) or Test Mode (FALSE).
	BOOL	m_bShowGrid;				///< Display (TRUE) or hide (FALSE) the grid in the view.
	BOOL	m_bFitToView;				///< Resize automatically the component to entirely fit the view.
	BOOL	m_bDrawPred;				// Display Prediction
	BOOL	m_bHidePred;				// Hide Prediction

	CSize	m_sDrawSize;				///< Current size of the view (used to adjust the sliders).

	//int		m_nCurrTTask;			// OBSOLETE: Zero-based index of the current task performed by learner.

// Operations
public:
	bool IsViewActive();

	CSimulDoc* GetDocument();
	CFormatAnimation*	GetFormats();
	int						GetTranslation();
	//CDlgActionGraph* GetActions();

	virtual void PaintAnim(CDC* pDC);      // overridden to draw this view

	BOOL CreateStyleBar();

	BOOL OnUpdateData();									// Response to data update
	BOOL OnUpdateTimer();									// Response to timer update
	BOOL OnUpdateBreakPoint(int nBPTime,int nBPType);		// Response to a breakpoint
	BOOL OnUpdateHypothesis(CUserData *pData);				// Response to an hypothesis
	BOOL OnUpdateAction(CUserData *pData);					// Response to an action
	BOOL OnUpdateMapRelation(CTranslationInfo *mTInfo );	// Response to a MAP RELATION 


// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CViewAnimat)
	public:
	virtual BOOL PreTranslateMessage(MSG* pMsg);
	virtual void Serialize(CArchive& ar);
	protected:
	virtual void OnDraw(CDC* pDC);      // overridden to draw this view
	virtual void OnInitialUpdate();     // first time after construct
	virtual BOOL PreCreateWindow(CREATESTRUCT& cs);
	virtual void OnUpdate(CView* pSender, LPARAM lHint, CObject* pHint);
	virtual BOOL OnPreparePrinting(CPrintInfo* pInfo);
	virtual void OnEndPrinting(CDC* pDC, CPrintInfo* pInfo);
	virtual void OnBeginPrinting(CDC* pDC, CPrintInfo* pInfo);
	virtual void OnPrint(CDC* pDC, CPrintInfo* pInfo);
	//}}AFX_VIRTUAL


// Implementation
protected:
	virtual ~CViewAnimat();
#ifdef _DEBUG
	virtual void AssertValid() const;
	virtual void Dump(CDumpContext& dc) const;
#endif

	BOOL CreateNewObject(CAnimObject *pObj=NULL);
	void TranslateObjects(int dX,int dY);
	void AlignObjects(int dX,int dY);
	// Generated message map functions
	//{{AFX_MSG(CViewAnimat)
	afx_msg void OnMouseMove(UINT nFlags, CPoint point);
	afx_msg void OnLButtonDown(UINT nFlags, CPoint point);
	afx_msg void OnLButtonDblClk(UINT nFlags, CPoint point);
	afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
	afx_msg void OnSize(UINT nType, int cx, int cy);
	afx_msg BOOL OnEraseBkgnd(CDC* pDC);
	afx_msg BOOL OnSetCursor(CWnd* pWnd, UINT nHitTest, UINT message);
	afx_msg void OnUpdateHSGrid(CCmdUI* pCmdUI);
	afx_msg void OnHideShowGrid();
	afx_msg void OnUpdateEditCmd(CCmdUI* pCmdUI);
	afx_msg void OnEditCopy();
	afx_msg void OnEditPaste();
	afx_msg void OnEditCut();
	afx_msg void OnEditDelete();
	afx_msg void OnEditSelectAll();
	afx_msg void OnUpdateComponent(CCmdUI* pCmdUI);
	afx_msg void OnNextExpSet();
	afx_msg void OnPrevExpSet();
	afx_msg void OnSendForward();
	afx_msg void OnSendBackward();
	afx_msg void OnUpdateAddInSector(CCmdUI* pCmdUI);
	afx_msg void OnAddInSector();
	afx_msg void OnContextMenu(CWnd* pWnd, CPoint point);
	afx_msg void OnShowAlignTool();
	afx_msg void OnUpdateAlignTool(CCmdUI* pCmdUI);
	afx_msg void OnShowComponentTool();
	afx_msg void OnUpdateComponentTool(CCmdUI* pCmdUI);
	afx_msg void OnKillFocus(CWnd* pNewWnd);
	afx_msg void OnKeyDown(UINT nChar, UINT nRepCnt, UINT nFlags);
	afx_msg void OnSetFocus(CWnd* pOldWnd);
	afx_msg void OnDestroy();
	afx_msg void OnShowProperties();
	afx_msg void OnUpdateShowProperties(CCmdUI* pCmdUI);
	//}}AFX_MSG
	afx_msg void OnNewComponent(UINT nID);
	afx_msg void OnSelectComponent();
	afx_msg void OnUpdateSelectComponent(CCmdUI* pCmdUI);
	afx_msg void OnSetAlignment(UINT nID);
	afx_msg void OnUpdateSetAlignment(CCmdUI* pCmdUI);
	afx_msg LRESULT OnUpdateInitContent(WPARAM, LPARAM); 
	afx_msg LRESULT OnActivateER(WPARAM, LPARAM); 
	afx_msg void OnSelChangeExpSet();
	afx_msg void OnTranslationTasks(UINT nID);
	afx_msg void OnUpdateTransTasks(CCmdUI* pCmdUI);
	LRESULT OnUpdateObjTooltip(WPARAM wp, LPARAM lp=0);
	DECLARE_MESSAGE_MAP()
};


#ifndef _DEBUG  // debug version in SimulView.cpp
inline CSimulDoc* CViewAnimat::GetDocument()
   { return (CSimulDoc*)m_pDocument; }
#endif

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SIMULANIMAT_H__0C4BC7A5_F381_11D3_A2F4_00D0B71C8709__INCLUDED_)
