//////////////////////////////////////////////////////////////////////
/// @file XYGraphData.h
/// @brief Interface for the CPhasePlotData class.
///
/// This file defines the CPhasePlotData class and related typedef, used in 
/// both the CViewGraph and CViewPhasePlot classes.
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_XYGRAPHDATA_H__F8B8EA23_F0C5_11D6_B8E1_00D0B71C8709__INCLUDED_)
#define AFX_XYGRAPHDATA_H__F8B8EA23_F0C5_11D6_B8E1_00D0B71C8709__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

/////////////////////////////////////////////////////////////////////////////
/// class storing information about the outcomes to be displayed in a graph-based
/// External Representation, either the X-Time Graph or the phaseplot.
/// Each instance defines which entity is graphed on the X-axis and Y-axis (resp.
/// #m_nXData and #m_nYData), which Experimental Set (#m_nExpSet) is used to generate the data.
/// It also defines the name of the graph to be displayed on the legend (#m_strName) 
/// and the color used to draw the curve.
/// The data-points to be displayed are stored in two dynamic arrays, one for each axis
/// (#m_pXaxis #m_pYaxis).
/////////////////////////////////////////////////////////////////////////////
class CPhasePlotData: public CObject
{
public:
	BOOL		m_bPred;		///< TRUE if this set of data is a prediction, FALSE if it is an outcome
	BOOL		m_bEditable;	///< TRUE if this set of data can be modified by user
	int			m_bSelected;	///< TRUE if this dataset is currently selected by user.

	int			m_nExpSet;		///< Zero-based index of the Experimental Set (see CLearningUnit::m_cExpSet) these data are generated with.
	int			m_nXData;		///< Zero-based index of the outcome (see CLearningUnit::m_cOutComesSet) used to generate the data on the X-axis.
	int			m_nYData;		///< Zero-based index of the outcome (see CLearningUnit::m_cOutComesSet) used to generate the data on the Y-axis.
	int			m_nData;		///< The number of data-point generated by the simulation (time-steps).
	
	double		*m_pXaxis;		///< Pointer to the array of double that will store the X-axis data-points generated by the model.
	double		*m_pYaxis;		///< Pointer to the array of double that will store the Y-axis data-points generated by the model.

	CString		m_strName;		///< Name of this dataset (usually the name of the outcome).
	COLORREF	m_clrData;		///< Default color used to display this dataset.

	CPhasePlotData(int nb);
	~CPhasePlotData();
};

typedef CTypedPtrArray<CObArray,CPhasePlotData*>	CxPPDataSet;	///< Set of CPhasePlotData

#endif // !defined(AFX_XYGRAPHDATA_H__F8B8EA23_F0C5_11D6_B8E1_00D0B71C8709__INCLUDED_)
