//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DEMIST.rc
//
#define IDC_SELECT_NODE                 12
#define IDC_UNSELECT_NODE               13
#define IDC_DISABLE_NODE                15
#define IDC_ENABLE_NODE                 16
#define IDD_ABOUTBOX                    100
#define IDD_SIMULPARAM_FORM             102
#define IDD_SIMULTIMER_FORM             104
#define IDD_SELECTPARAM                 106
#define IDD_ANIMVALUE_PAGE              114
#define IDD_ANIMSHAPE_PAGE              115
#define IDD_DEFINE_PARAM                119
#define IDR_MAINFRAME                   120
#define IDD_DEFINE_EXPSET               122
#define IDD_FORMAT_TABLE                123
#define IDD_FORMAT_GRAPH                124
#define IDD_IDENTITY                    127
#define IDB_TREE_CTRL_OPTIONS           129
#define IDR_SIMULTYPE                   130
#define IDC_SPLITTER                    130
#define IDB_PUSHPIN                     131
#define IDR_VIEWCONTROLLER              131
#define IDD_WELCOMEBAR                  131
#define IDR_SIMULPIE                    132
#define IDR_SIMULTEXT                   133
#define IDC_DELETE                      133
#define IDR_SIMULGRAPH                  134
#define IDR_SIMULANIM                   135
#define IDR_SIMULTABLE                  136
#define IDR_SIMULHISTOGRAM              137
#define IDR_SIMULXYGRAPH                138
#define IDR_SIMULTIMER                  139
#define IDR_SIMULEQUATION               140
#define IDR_SIMULRULER                  141
#define IDR_SIMULGLASS                  142
#define IDR_SIMULBOOK                   143
#define IDR_SIMULGRAPHLOG               144
#define IDR_SIMULNODE                   145
#define IDR_SIMULTHERMO                 146
#define IDR_SIMUL_CONTEXT               147
#define IDR_SIMUL_WELCOME               148
#define IDD_DEFINEOUTCOME_DLG           150
#define IDD_EDITINTERVAL                152
#define IDD_VIEW_CONTROLLER             153
#define IDB_SQUARE                      154
#define IDR_SIMULPARAM_TMPL             155
#define IDR_VIEWNEWLISTMODEL_TMPL       158
#define IDD_PREF_SIMUL_PAGE             159
#define IDR_VIEW_MULTIPANES             159
#define IDB_ER_ICONS                    160
#define IDD_SORTERDLG_DIALOG            161
#define IDD_MODEL_VARIABLE              162
#define IDD_INFOTASK_DIALOG             163
#define IDB_VAR_ICONS                   164
#define IDD_BPMESSAGE_DLG               165
#define IDI_ICONPREV                    166
#define IDI_ICONNEXT                    167
#define IDI_ICONRUN                     168
#define IDB_RADIAL_BACKGROUND_BITMAP    169
#define IDR_ANIM_CTX                    170
#define IDD_EDIT_VALUE                  171
#define IDR_VIEWBUILDMODEL_TMPL         172
#define IDR_VIEWHTMLWELCOME_TMPL        174
#define IDI_VIEW_ICON                   178
#define IDI_VIEW_LIST                   179
#define IDR_SIMULANIM_ALIGN             180
#define IDR_SIMULANIM_CPNT              181
#define IDR_DROP_OPEN                   182
#define IDR_TASKBAR                     182
#define IDR_TASKBAR_BIS                 183
#define IDR_DROP_TEXT                   183
#define IDR_MAINFRAME_BIS               184
#define IDD_ANIMOBJ_PROPDLG             200
#define IDD_ANIMTEXT_PAGE               201
#define IDD_ANIMOBJPOS_PAGE             202
#define IDD_ANIMPICT_PAGE               203
#define IDD_DEFINE_MODEL                204
#define IDD_DEFINE_MER                  205
#define IDD_ANIMDENSITY_PAGE            206
#define IDD_FORMAT_TABLE2               207
#define IDD_FORMAT_ANIMATION            208
#define IDD_FORMAT_GRAPH2               210
#define IDD_FORMAT_PARAMETER            211
#define IDD_SIMULTABLE_FORM             212
#define IDD_FORMAT_PHASEPLOT            213
#define IDD_ANIMOBJSIZE_PAGE            214
#define IDD_ANIMLINK_PAGE               215
#define IDD_ANIMSECTOR_PAGE             216
#define IDD_ANIMPICTDENS_PAGE           217
#define IDD_ER_TRANSLATION              218
#define IDD_PREF_CAT_PAGE               219
#define IDD_PREF_CONFIG_PAGE            220
#define IDD_DEFINE_OUTCOME_DLG          221
#define IDD_FORMAT_CHART                222
#define IDD_FORMAT_TEXT                 223
#define IDD_ER_FORMAT                   224
#define IDD_MODEL_MODEL                 225
#define IDD_MODEL_ADD                   226
#define IDD_ANIMATION_SELECT            227
#define IDD_MODEL_BUILD                 228
#define IDD_MODEL_BUILDPROP             229
#define IDD_LU_MODELPAGE                230
#define IDD_LU_EXPSETPAGE               231
#define IDD_LU_INSTRUCTPAGE             232
#define IDD_LU_MERPAGE                  233
#define IDD_ER_OUTCOME                  234
#define IDD_ER_EXTREP                   235
#define IDD_ER_OUTCOME_XY               236
#define IDD_ANIMPOLYGON_PAGE            237
#define IDD_ANIMINTER_PAGE              238
#define IDB_SMOKES                      500
#define IDB_BOOKS                       501
#define IDB_BEANY                       502
#define IDB_ROUND                       503
#define IDB_ANIM_COMPONENT              504
#define IDB_TIME_BREAKPOINT             507
#define IDB_CONTROLLER                  527
#define IDB_CONTR_TIMER                 528
#define IDB_ANIM_SELECTOR               529
#define IDB_TIME_SMBREAKPOINT           530
#define IDB_ANTRED                      531
#define IDB_ANTBLACK                    532
#define IDB_RATKANG                     533
#define IDB_RATPOCK                     534
#define IDB_FINRED                      535
#define IDB_FINGREEN                    536
#define IDB_BARNACLE                    537
#define IDB_MERSORT                     538
#define IDB_ANIM_CPNTPAGE               539
#define IDB_BREAKPOINT_BANNER           540
#define IDB_BP_INFO                     541
#define IDB_BP_ACTION                   542
#define IDB_BP_HYPOT                    543
#define IDB_BP_TEST                     544
#define IDB_MODEL_ICON                  545
#define IDB_MODEL_DESIGN                546
#define IDB_MODEL_LU                    547
#define IDB_MODEL_ERS                   548
#define IDB_TIME_ADDBP                  549
#define IDC_LISTPARAM                   1000
#define IDC_TREE                        1000
#define IDC_SLIDER1                     1000
#define IDC_VALUETAB                    1002
#define IDC_GRAPH_TITLE                 1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_GRAPH_CH_TITLE              1004
#define IDC_EDIT3                       1005
#define IDC_GRAPH_CH_COLOR              1005
#define IDC_EDIT4                       1006
#define IDC_TITLE_STRING                1006
#define IDC_EDIT5                       1007
#define IDC_VALUE                       1007
#define IDC_EDIT6                       1008
#define IDC_UPDATE                      1009
#define IDC_DEFAULT                     1010
#define IDC_EXPSET_DEFAULT              1010
#define IDC_SPINCARCAP                  1012
#define IDC_X1                          1012
#define IDC_SPINCOVER                   1013
#define IDC_PENSIZE                     1013
#define IDC_X2                          1013
#define IDC_SPINSIZE                    1014
#define IDC_TIMESLIDER                  1015
#define IDC_SPINPREY                    1015
#define IDC_MIN                         1015
#define IDC_START                       1016
#define IDC_SPINPRED                    1016
#define IDC_MAX                         1016
#define IDC_Y1                          1016
#define IDC_GRAPHSTYLE                  1017
#define IDC_Y2                          1017
#define IDC_START_PT                    1017
#define IDC_STOP                        1017
#define IDC_EDITTEXT                    1018
#define IDC_MARKERS                     1018
#define IDC_GEN_GRAPH_PROPS_AXIS        1018
#define IDC_XTITLE                      1018
#define IDC_END_PT                      1018
#define IDC_APPLY                       1018
#define IDC_SETFONT                     1019
#define IDC_RESET                       1019
#define IDC_XUOM                        1020
#define IDC_ADD                         1020
#define IDC_GRAPH_CHOICE                1021
#define IDC_YTITLE                      1021
#define IDC_RESTART                     1021
#define IDC_ALIGN                       1022
#define IDC_YUOM                        1022
#define IDC_NEXTUNIT                    1022
#define IDC_GRAPH_HIDESHOW              1023
#define IDC_NEWBP                       1023
#define IDC_NEWBP_A                     1023
#define IDC_HORIZ                       1024
#define IDC_GRAPH_POINTMARKS            1024
#define IDC_VERTIC                      1025
#define IDC_NEWBP2                      1025
#define IDC_NEWBP_H                     1025
#define IDC_XSCALE                      1026
#define IDC_GRAPH_MOUSECOORDS           1026
#define IDC_YSCALE                      1027
#define IDC_BROWSE                      1027
#define IDC_XAXIS_PRECISION             1027
#define IDC_GRAPHS_SHOWALL              1028
#define IDC_YAXIS_PRECISION             1028
#define IDC_XDEF                        1028
#define IDC_YDEF                        1029
#define IDC_DEL                         1029
#define IDC_BMPFILE                     1030
#define IDC_WDEF                        1030
#define IDC_WSCALE                      1031
#define IDC_BACKGROUND                  1032
#define IDC_CBWIDTH                     1032
#define IDC_DATALIST                    1033
#define IDC_HDEF                        1033
#define IDC_PRECISION                   1034
#define IDC_HSCALE                      1034
#define IDC_SPINPREC                    1035
#define IDC_STEP                        1035
#define IDC_CBHEIGHT                    1035
#define IDC_LCOLOR                      1036
#define IDC_FROM                        1036
#define IDC_ADEF                        1036
#define IDC_BCOLOR                      1037
#define IDC_TO                          1037
#define IDC_VAL_MAX                     1037
#define IDC_ASCALE                      1037
#define IDC_NEGCOLOR                    1038
#define IDC_VAL_INIT                    1038
#define IDC_LSTYLE                      1038
#define IDC_CBAREA                      1038
#define IDC_DESC                        1039
#define IDC_EXPSET_INIT                 1048
#define IDC_MODEL                       1050
#define IDC_RUNMODE                     1051
#define IDC_CATEGORY                    1051
#define IDC_ER_CAT                      1052
#define IDC_TIMER_SPIN                  1053
#define IDC_TIMER_LOCK                  1054
#define IDC_EXPSET_LOCK                 1055
#define IDC_EXPSET                      1056
#define IDC_EXPSET_ADD                  1057
#define IDC_EXPSET_DEL                  1058
#define IDC_BP_FIRST                    1059
#define IDC_EXPSET_DEF                  1060
#define IDC_EXPSET_DUP                  1061
#define IDC_TIMER                       1062
#define IDC_EXPSET_NAME                 1066
#define IDC_ORDER_SPIN                  1066
#define IDC_EXPSET_PARAM                1067
#define IDC_ORDER_ERNB                  1067
#define IDC_OUTCOMES                    1068
#define IDC_FORMAT                      1069
#define IDC_OPERATOR                    1070
#define IDC_MERICON                     1071
#define IDC_EXTREP                      1072
#define IDC_START_OPEN                  1073
#define IDC_TRANS_MODE                  1074
#define IDC_DEFAULT_OUTCOMES            1075
#define IDC_SPIN1                       1076
#define IDC_SYNC                        1076
#define IDC_CHECKMAX                    1077
#define IDC_CHECKMIN                    1078
#define IDC_CHECKCELL                   1078
#define IDC_CHECKNEG                    1079
#define IDC_CHECKLINE                   1079
#define IDC_MAXCOLOR                    1080
#define IDC_CHECKCOL                    1080
#define IDC_MINCOLOR                    1081
#define IDC_DEFCOLOR                    1082
#define IDC_DEFAULT_RESTORE             1088
#define IDC_PARAM_TREE                  1091
#define IDC_VAL_MIN                     1093
#define IDC_DEFUNIT                     1095
#define IDC_DEFICON                     1096
#define IDC_SHOWVALUES1                 1098
#define IDC_DRAG                        1098
#define IDC_CONNECTOR                   1098
#define IDC_TITLE_TEXT                  1098
#define IDC_BP_STYLE                    1098
#define IDC_DIM                         1098
#define IDC_TRANSLATION                 1098
#define IDC_LEVEL                       1098
#define IDC_MODE                        1098
#define IDC_EDIT_RD2                    1099
#define IDC_SHOWVALUES3                 1099
#define IDC_DRAG2                       1099
#define IDC_CONNECTOR2                  1099
#define IDC_TITLE_VALUE                 1099
#define IDC_BP_STYLE2                   1099
#define IDC_TRANSLATION2                1099
#define IDC_MODE2                       1099
#define IDC_ALIGN2                      1099
#define IDC_TAB_EXPSET                  1100
#define IDC_EDIT_RD3                    1100
#define IDC_SHOWVALUES2                 1100
#define IDC_DRAG3                       1100
#define IDC_CONNECTOR3                  1100
#define IDC_DIM2                        1100
#define IDC_TRANSLATION3                1100
#define IDC_BP_STYLE3                   1100
#define IDC_LEVEL2                      1100
#define IDC_VIEW_LIST                   1100
#define IDC_COMBO_CSEL                  1101
#define IDC_DRAG4                       1101
#define IDC_DIM3                        1101
#define IDC_TRANSLATION4                1101
#define IDC_LEVEL3                      1101
#define IDC_BP_STYLE4                   1101
#define IDC_CONNECTOR4                  1101
#define IDC_COMBO_LSEL                  1102
#define IDC_TRANSLATION5                1102
#define IDC_DRAG5                       1102
#define IDC_COMBO_CLSEL                 1103
#define IDC_DRAG6                       1103
#define IDC_DRAG7                       1104
#define IDC_DISPLAY_AXE                 1105
#define IDC_DRAG8                       1105
#define IDC_DISPLAY_LEG                 1106
#define IDC_AUTOSCALE                   1107
#define IDC_DISPLAY_LEG2                1107
#define IDC_SCALE_XMIN                  1108
#define IDC_DISPLAY_LEG3                1108
#define IDC_SCALE_XMAX                  1109
#define IDC_SCALE_YMIN                  1110
#define IDC_DESCRIPTION                 1110
#define IDC_SCALE_YMAX                  1111
#define IDC_OBJECTTREE                  1111
#define IDC_EDIT_RD1                    1112
#define IDC_DISPLAY_VALUES              1112
#define IDC_DISPLAY_TIPS                1113
#define IDC_POP_ADD                     1114
#define IDC_DISPLAY_ISOCLINE            1114
#define IDC_DISPLAY_STABPT              1115
#define IDC_POP_DEL                     1116
#define IDC_OUTC_COMBO                  1119
#define IDC_STATIC_PARAM                1123
#define IDC_STATIC_INIT                 1124
#define IDC_EDIT_PWD                    1126
#define IDC_COMBO_NAME                  1127
#define IDC_TRICK                       1128
#define IDC_ANIMATION                   1129
#define IDC_SHOWLEGEND                  1130
#define IDC_ATTACHED                    1131
#define IDC_FITTOVIEW                   1132
#define IDC_SHOWTRACE                   1132
#define IDC_SHOWAXIS                    1133
#define IDC_GRID                        1135
#define IDC_COMPONENT                   1137
#define IDC_DEFICON2                    1138
#define IDC_SCALE                       1139
#define IDC_DISPLAY_CURRTIME            1140
#define IDC_LSIZE                       1142
#define IDC_SPIN_SIZE                   1143
#define IDC_TRANSCOLOR                  1144
#define IDC_SAVE                        1145
#define IDC_LOAD                        1146
#define IDC_BEGIN                       1146
#define IDC_RUN                         1147
#define IDC_END                         1148
#define IDC_PREV                        1149
#define IDC_NEXT                        1150
#define IDC_EXPAND                      1151
#define IDC_PREVSTEP                    1152
#define IDC_ARROW_START                 1153
#define IDC_NEXTSTEP                    1153
#define IDC_ARROW_END                   1154
#define IDC_SHAPE                       1154
#define IDC_LOCKED                      1155
#define IDC_DISPLAY_NAME                1158
#define IDC_DISPLAY_UNIT                1159
#define IDC_PREVTIME                    1160
#define IDC_MYSTATIC                    1161
#define IDC_SYNCDEF                     1162
#define IDC_BP_DESCR                    1163
#define IDC_LOG                         1164
#define IDC_DATA                        1165
#define IDC_SHOWVALUE                   1166
#define IDC_DELTA                       1167
#define IDC_FOLDER                      1168
#define IDC_TOPEN                       1169
#define IDC_TCLOSE                      1170
#define IDC_TSWITCH                     1171
#define IDC_X_OUTCOME                   1171
#define IDC_TRUN                        1172
#define IDC_Y_OUTCOME                   1172
#define IDC_TPAUSE                      1173
#define IDC_X_STAB                      1173
#define IDC_SAMPLE                      1173
#define IDC_TREVIEW                     1174
#define IDC_Y_STAB                      1174
#define IDC_PARAMCOLOR                  1174
#define IDC_X_ISO1                      1175
#define IDC_VARCOLOR                    1175
#define IDC_Y_ISO1                      1176
#define IDC_CSTCOLOR                    1176
#define IDC_X_ISO2                      1177
#define IDC_PARAM                       1177
#define IDC_Y_ISO2                      1178
#define IDC_TASK                        1179
#define IDC_ICON1                       1182
#define ID_WELCOME_START                1183
#define IDC_HTMLDOC                     1184
#define IDC_ICON2                       1185
#define IDC_LUNAME                      1185
#define ID_WELCOME_NEXT                 1185
#define IDC_ICON3                       1186
#define ID_WELCOME_CURRENT              1186
#define IDC_ICON4                       1187
#define IDC_ISO1                        1187
#define IDC_ISO2                        1188
#define IDC_NAME                        1188
#define IDC_MODEL_LIST                  1192
#define IDC_MODEL_ADD                   1193
#define IDC_MODEL_DEL                   1194
#define IDC_ADD_TAB                     1194
#define IDC_ADD_LIST                    1195
#define IDC_ADD_DESC                    1196
#define IDC_SIM_SPEED_AUTH              1197
#define IDC_SIM_SPEED_LEARN             1198
#define IDC_OBJ_LIST                    1200
#define IDC_VIEW_ICON                   1205
#define IDC_VIEW_LOAD                   1206
#define IDC_LCOLOR_OBJ                  1207
#define IDC_VIEW_SAVE                   1207
#define IDC_BCOLOR_OBJ                  1208
#define IDC_RADIO_HYP                   1210
#define IDC_RADIO_HYP2                  1211
#define IDC_SIM_PASTCLR                 1211
#define IDC_SIM_FUTURECLR               1212
#define IDC_SHOWLABEL                   1216
#define IDC_MER_LIST                    1220
#define IDC_MER_UP                      1221
#define IDC_MER_DOWN                    1222
#define IDC_BP_NAME                     1223
#define IDC_BP_DESC                     1224
#define IDC_BP_ICON                     1225
#define IDC_MER_SEQUENCE                1226
#define IDC_CATLIST                     1230
#define IDC_ICONSPIN                    1231
#define IDC_BUTTON1                     1232
#define IDC_BMODEL_VAL                  1239
#define IDC_BMODEL_EQUATION             1240
#define IDC_BMODEL_PROP                 1241
#define IDC_BMODEL_EQS                  1242
#define IDD_MODEL_BUILDPROP_NUM         1244
#define IDD_MODEL_BUILDPROP_H           1245
#define IDD_SIM_RANGE_X                 1246
#define IDC_OUTC_COMBOEX                1247
#define IDD_SIM_RANGE_Y                 1247
#define IDD_SIM_RANGE_D                 1248
#define IDC_DATALISTEX                  1252
#define IDC_INSTR_SLIDER                1254
#define IDC_SIM_MODEL                   1255
#define IDC_SIM_LUNAME                  1256
#define IDD_SIM_METHOD                  1257
#define IDD_SIM_H                       1258
#define IDC_SIM_TIMER                   1259
#define IDC_SIM_TIMERSPIN               1260
#define IDC_INSTR_FIRST                 1261
#define IDC_INSTR_HTMLDOC               1262
#define IDC_INSTR_BROWSE                1263
#define IDC_MERS_ORDER                  1264
#define IDC_INSTR_ACTIONS               1264
#define IDC_MERS_ORDERSPIN              1265
#define IDC_MERS_SHOWLABEL              1266
#define IDC_ER_SYNCDEF                  1267
#define IDC_MERS_MULTIPANE              1267
#define IDC_ER_GRID                     1268
#define IDC_ER_DEFAULT                  1269
#define IDC_ER_RESTORE                  1270
#define IDC_ER_EXTREP                   1271
#define IDC_ER_RUNMODE                  1272
#define IDC_ER_NAME                     1273
#define IDC_ER_START                    1274
#define IDC_ER_ICON                     1275
#define IDC_ER_ICONSPIN                 1276
#define IDC_ER_XOUTCOME                 1277
#define IDC_ER_KEEPOPEN                 1277
#define IDC_ER_YOUTCOME                 1278
#define IDC_ER_EXPSETGRID               1279
#define IDC_ER_XISO1                    1281
#define IDC_ER_YISO1                    1282
#define IDC_ER_XISO2                    1283
#define IDC_ER_YISO2                    1284
#define IDC_ER_XSTAB                    1285
#define IDC_ER_YSTAB                    1286
#define IDC_BP_VALUE                    1287
#define IDC_BP_HTMLDOC                  1288
#define IDC_BP_BROWSE                   1289
#define IDC_POLYGON                     1291
#define IDC_POLYG_ADD                   1292
#define IDC_POLYG_DEL                   1293
#define IDC_BP_TITLE                    1294
#define IDC_RICHEDIT2                   1295
#define IDC_RESIZE_W                    1296
#define IDC_DRAG_X                      1297
#define IDC_DRAG_Y                      1298
#define IDC_RESIZE_H                    1299
#define IDC_MAPREL                      1300
#define ERR_EXPSET_LOWERLIMIT           2000
#define ERR_LUNIT_LOWERLIMIT            2001
#define ERR_LUNIT_MAXERACTIVE           2002
#define ERR_SIMULATION_RESTART          2003
#define ID_CHART_BAR                    32774
#define ID_CHART_LINE                   32775
#define ID_CHART_PIE                    32776
#define ID_VIEW_FULLSCREEN              32777
#define ID_VIEW_CHART                   32779
#define ID_VIEW_PARAM                   32780
#define ID_VIEW_TABLE                   32781
#define ID_VIEW_MODEL                   32782
#define ID_VIEW_GRAPH                   32783
#define ID_VIEW_ANIM                    32784
#define ID_VIEW_TIMER                   32785
#define ID_VIEW_XYGRAPH                 32786
#define ID_VIEW_DESIGN_SIMULATION       32787
#define ID_VIEW_DESIGN_INSTRUCTION      32788
#define ID_VIEW_CONTROLLER              32789
#define ID_SELECTDATA                   32790
#define ID_ANIMATION_SHOWGRID           32791
#define ID_VIEW_WELCOME                 32792
#define IDS_VIEW_WELCOME                32793
#define ID_INSTRUCTION_ADDUNIT          32801
#define ID_INSTRUCTION_ADDER            32802
#define ID_INSTRUCTION_UNITPROP         32803
#define ID_INSTRUCTION_ERPROP           32804
#define ID_INSTRUCTION_TRYER            32805
#define ID_INSTRUCTION_AUTHMODE         32808
#define ID_ANIMATION_TEXT               32813
#define ID_ANIMATION_IMAGE              32814
#define ID_ANIMATION_VALUE              32815
#define ID_ANIMATION_RECT               32816
#define ID_ANIMATION_DENSITY            32817
#define ID_ANIMATION_CONNECT            32818
#define ID_ANIMATION_SECTOR             32819
#define ID_FILE_PREF                    32820
#define ID_FILE_SWITCHMODE              32821
#define ID_PARAMETERS_UPDATECHANGES     32822
#define ID_PARAMETERS_RESETVALUES       32823
#define ID_PARAMETERS_ADDEXPSET         32824
#define ID_PARAMETERS_REMOVEEXPSET      32825
#define ID_BUTTON32833                  32833
#define ID_ANIMATION_FORWARD            32836
#define ID_ANIMATION_BACKWARD           32837
#define ID_ANIMATION_NEXTEXPSET         32839
#define ID_ANIMATION_PREVEXPSET         32840
#define ID_ANIMATION_SELECTEXPSET       32841
#define ID_XYGRAPH_SCALETYPE_LINEAR     32842
#define ID_XYGRAPH_SCALETYPE_XLOG       32843
#define ID_XYGRAPH_SCALETYPE_YLOG       32844
#define ID_XYGRAPH_SCALETYPE_XYLOG      32845
#define ID_EDIT_SELECTALL               32846
#define ID_TIMER_PLAY                   32848
#define ID_INSTRUCTION_SAVEPOS          32851
#define ID_ANIMATION_ADDSECTOR          32853
#define ID_SIMULATION_UPDATEMODELS      32858
#define ID_TIMER_RESTART                32859
#define ID_TIMER_STOP                   32860
#define ID_ANIM_ALIGNLEFT               32861
#define ID_ANIM_ALIGNCENTER             32862
#define ID_ANIM_ALIGNRIGHT              32863
#define ID_ANIM_ALIGNTOP                32864
#define ID_ANIM_ALIGNMIDDLE             32865
#define ID_ANIM_ALIGNBOTTOM             32866
#define ID_ANIM_ALIGNHOR                32867
#define ID_ANIM_ALIGNVER                32868
#define ID_ANIM_CONSTRUCTION            32869
#define ID_ANIM_ALIGN                   32870
#define ID_ANIMATION_CATER              32871
#define ID_TASK_MAPFACT                 32872
#define ID_TASK_MAPRELATION             32873
#define ID_TASK_SUPPORTACTION           32874
#define ID_TASK_CANCELTASK              32875
#define ID_VIEW_TASKBAR                 32876
#define ID_INSTRUCTION_NEXTLU           32877
#define ID_INSTRUCTION_PREVLU           32878
#define ID_CONTROLLER_NEXTUNIT          32879
#define ID_ANIMATION_SHOWPROPERTIES     32880
#define ID_TRANS_INDEPENDENT            32883
#define ID_TRANS_MAPFACT                32884
#define ID_TRANS_MAPRELATION            32885
#define ID_TRANS_SUPPORTACTION          32886
#define ID_INSTRUCTION_SORTER           32886
#define ID_TRANS_DYNALINKED             32887
#define ID_VIEW_ERS                     32888
#define ID_ANIMATION_POLYGON            32889
#define ID_INSTRUCTION_MULTIPANES       32890
#define ID_VIEW_EXTREP1                 32891
#define ID_VIEW_EXTREP2                 32892
#define ID_VIEW_EXTREP3                 32893
#define ID_VIEW_EXTREP4                 32894
#define ID_VIEW_EXTREP5                 32895
#define ID_VIEW_EXTREP6                 32896
#define ID_VIEW_EXTREP7                 32897
#define ID_VIEW_EXTREP8                 32898
#define ID_VIEW_EXTREP9                 32899
#define ID_VIEW_EXTREP10                32900
#define ID_VIEW_EXTREP11                32901
#define ID_VIEW_EXTREP12                32902
#define ID_VIEW_EXTREP13                32903
#define ID_VIEW_EXTREP14                32904
#define ID_VIEW_EXTREP15                32905
#define ID_VIEW_EXTREP16                32906
#define ID_VIEW_EXTREP17                32907
#define ID_VIEW_EXTREP18                32908
#define ID_VIEW_EXTREP19                32909
#define ID_VIEW_EXTREP20                32910
#define ID_INDICATOR_MODE               33000
#define ID_INDICATOR_MODE2              33001
#define ID_CONTR_START                  33002
#define ID_CONTR_STOP                   33003
#define ID_CONTR_RESTART                33004
#define ID_CONTR_BACK                   33005
#define ID_CONTR_FOR                    33006
#define ID_CONTR_PAUSE                  33007
#define ID_CONTR_BEGIN                  33008
#define ID_CONTR_END                    33009
#define ID_CONTR_TASK                   33010
#define ID_CONTR_STEPP                  33011
#define ID_CONTR_STEPN                  33012
#define ID_CONTR_ADDA                   33013
#define ID_CONTR_ADDH                   33014
#define ID_ANIMATION_SELECTOBJECT       40000
#define MSG_LU_ACT_INIT                 57400
#define MSG_LU_ACT_CURRENT              57401
#define MSG_LU_ACT_PREVIOUS             57402
#define MSG_LU_ACT_NEXT                 57403
#define MSG_HTML_CREATE                 57410
#define ERR_NOSIMMODEL                  57500
#define AFX_IDS_DELETE_COMPONENT        61446
#define IDC_OPTIONSTREE_OPTIONS         61447
#define IDC_OLDVALUE                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        191
#define _APS_NEXT_COMMAND_VALUE         32894
#define _APS_NEXT_CONTROL_VALUE         1297
#define _APS_NEXT_SYMED_VALUE           175
#endif
#endif
